GET http://localhost:3001/api/filters/metadata/0

###

PATCH http://localhost:3001/api/filters/crop/0
Content-Type: application/json

{
	"width": 100,
	"height": 50,
	"top": 10,
	"left": 10
}

###

PATCH http://localhost:3001/api/filters/rotate/0
Content-Type: application/json

{
	"angle": 90
}

###

PATCH http://localhost:3001/api/filters/resize/0
Content-Type: application/json

{
	"width": 100,
	"height": 50
}

###

PATCH http://localhost:3001/api/filters/reformat/0
Content-Type: application/json

{
	"format": "png"
}

###

PATCH http://localhost:3001/api/filters/grayscale/0

###

PATCH http://localhost:3001/api/filters/flip/0

###

PATCH http://localhost:3001/api/filters/flop/0

###

PATCH http://localhost:3001/api/filters/negate/0

###

PATCH http://localhost:3001/api/filters/tint/0
Content-Type: application/json

{
	"r": 255,
	"g": 0,
	"b": 0
}
