GET http://localhost:3001/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0

###

GET http://localhost:3001/api/photos/6482348f63ebc76f4ae62537 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0

###

POST http://localhost:3001/api/photos HTTP/1.1
Content-Type: multipart/form-data; boundary=FormBoundary1234
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjI1OTgwNSwiZXhwIjoxNjg2MzQ2MjA1fQ.oCQtYY9lXM8VKDL99fTKyM9bkGkU-ROv3qWZv3S1GHU

--FormBoundary1234
Content-Disposition: form-data; name="photos"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

--FormBoundary1234
Content-Disposition: form-data; name="tags"
Content-Type: application/json

[]
--FormBoundary1234--

###

DELETE http://localhost:3001/api/photos/648354f83d4179a93c29f0b3 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0

###

PATCH http://localhost:3001/api/photos/64825628456233deb7e3606d HTTP/1.1
Content-Type: multipart/form-data; boundary=FormBoundary1234
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjI1OTgwNSwiZXhwIjoxNjg2MzQ2MjA1fQ.oCQtYY9lXM8VKDL99fTKyM9bkGkU-ROv3qWZv3S1GHU

--FormBoundary1234
Content-Disposition: form-data; name="photo"; filename="input_copy.webp"
Content-Type: image/jpeg

< ./input_copy.webp
--FormBoundary1234--

###

PATCH http://localhost:3001/api/photos/6482348f63ebc76f4ae62537/tags HTTP/1.1
Content-Type: application/json

{
	"name": "#new-tag",
	"popularity": 1233
}

###

PATCH http://localhost:3001/api/photos/0/tags/mass HTTP/1.1
Content-Type: application/json

[
	{
		"name": "#new-tag",
		"popularity": 1233
	},
	{
		"name": "#new-tag2",
		"popularity": 1233
	}
]

###

DELETE http://localhost:3001/api/photos/64823e65f851de737be110b8 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0


###

GET http://localhost:3001/api/photos/648241c41fa7b3163da94ce5/tags HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0


###

GET http://localhost:3001/api/uploads/upload_30ca0a4fcaa2c58326a92fcc1efa4802.jpg HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0
