GET http://localhost:3001/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjUwNTI2MSwiZXhwIjoxNjg3MTEwMDYxfQ.WICrI7hBbztp0O4AHYdFhDRed-KLk81H1i5Eteyk3bw

###

GET http://localhost:3001/api/photos/6482348f63ebc76f4ae62537 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0

###

POST http://localhost:3001/api/photos HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjUwNTI2MSwiZXhwIjoxNjg3MTEwMDYxfQ.WICrI7hBbztp0O4AHYdFhDRed-KLk81H1i5Eteyk3bw
Content-Type: multipart/form-data; boundary=FormBoundary1234

--FormBoundary1234
Content-Disposition: form-data; name="photos"; filename="input.jpg"
Content-Type: image/jpeg

< ./input.jpg

--FormBoundary1234
Content-Disposition: form-data; name="description"
Content-Type: text/plain

description

--FormBoundary1234
Content-Disposition: form-data; name="tags"
Content-Type: application/json

["#dupa", "#sraka"]
--FormBoundary1234--

###

DELETE http://localhost:3001/api/photos/648354f83d4179a93c29f0b3 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0

###

PATCH http://localhost:3001/api/photos/6482348f63ebc76f4ae62537 HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjUwNTI2MSwiZXhwIjoxNjg3MTEwMDYxfQ.WICrI7hBbztp0O4AHYdFhDRed-KLk81H1i5Eteyk3bw
Content-Type: application/json

{
	"description": "new description",
	"tags": ["#new-tag", "#new-tag2"]
}


###

GET http://localhost:3001/api/photos/user/mwojtyna HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0

###

GET http://localhost:3001/api/uploads/upload_0f75894a13631afdf3da3c0b585405a0.jpg HTTP/1.1
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0
