POST http://localhost:3001/api/user/register
Content-Type: application/json

{
	"name": "Mateusz",
	"lastName": "Wojtyna",
	"email": "user@domain.com",
	"password": "Zaq1@wsx"
}

###

GET http://localhost:3001/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjExODA2MiwiZXhwIjoxNjg2MTIxNjYyfQ.eDQOkfEpEeDfWm646Vk-XPepW6v4VZiUde4J8A4TIog

###

POST http://localhost:3001/api/user/login
Content-Type: application/json

{
	"email": "user@domain.com",
	"password": "1234"
}

###

GET http://localhost:3001/api/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjI1OTgwNSwiZXhwIjoxNjg2MzQ2MjA1fQ.oCQtYY9lXM8VKDL99fTKyM9bkGkU-ROv3qWZv3S1GHU

###

PATCH http://localhost:3001/api/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0
Content-Type: application/json

{
	"name": "Mateusz1",
	"lastName": "Wojtyna1"
}

###

POST http://localhost:3001/api/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjI1OTgwNSwiZXhwIjoxNjg2MzQ2MjA1fQ.oCQtYY9lXM8VKDL99fTKyM9bkGkU-ROv3qWZv3S1GHU
Content-Type: multipart/form-data; boundary=FormBoundary1234

--FormBoundary1234
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpg

< ./input.jpg
--FormBoundary1234--

###

GET http://localhost:3001/api/user/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0
