POST http://localhost:3001/api/user/register
Content-Type: application/json

{
	"name": "Mateusz",
	"lastName": "Wojtyna",
	"email": "user@domain.com",
	"password": "1234"
}

###

GET http://localhost:3001/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjExODA2MiwiZXhwIjoxNjg2MTIxNjYyfQ.eDQOkfEpEeDfWm646Vk-XPepW6v4VZiUde4J8A4TIog

###

POST http://localhost:3001/api/user/login
Content-Type: application/json

{
	"email": "user@domain.com",
	"password": "1234"
}

###

GET http://localhost:3001/api/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0

###

PATCH http://localhost:3001/api/user/profile
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0
Content-Type: application/json

{
	"name": "Mateusz1",
	"lastName": "Wojtyna1"
}

###

POST http://localhost:3001/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NTAxMDI3MCwiZXhwIjoxNjg1MDk2NjcwfQ.dpBKQA9neHQZQPNEUhCKe-1UYWTqQpicWdgYJlVkIzc
Content-Type: multipart/form-data; boundary=----FormBoundary12345

------FormBoundary12345
Content-Disposition: form-data; name="file"; filename="input.jpg"
Content-Type: image/jpg

< ./input.jpg
------FormBoundary12345

###

GET http://localhost:3001/api/user/logout
Cookie: token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NjAzNjQ3NiwiZXhwIjoxNjg2MTIyODc2fQ._HXvj2oTGvR3pAaemByMv3mK4qJJ36_Y5GGjvo51YN0
