GET http://localhost:3000/api/filters/metadata/0

###

PATCH http://localhost:3000/api/filters/crop/0
Content-Type: application/json

{
	"width": 100,
	"height": 50,
	"top": 10,
	"left": 10
}

###

PATCH http://localhost:3000/api/filters/rotate/0
Content-Type: application/json

{
	"angle": 90
}

###

PATCH http://localhost:3000/api/filters/resize/0
Content-Type: application/json

{
	"width": 100,
	"height": 50
}
