POST http://localhost:3000/api/user/register
Content-Type: application/json

{
	"name": "Mateusz",
	"lastName": "Wojtyna",
	"email": "user@domain.com",
	"password": "1234"
}

###

GET http://localhost:3000/api/user/confirm/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NTAwODQxMCwiZXhwIjoxNjg1MDEyMDEwfQ.sw9XZAVtJRGMySFjl3u6gYRzN07x8foVedFB27HKUUk

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
	"email": "user@domain.com",
	"password": "1234"
}

###

GET http://localhost:3000/api/user/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXJAZG9tYWluLmNvbSIsImlhdCI6MTY4NTAwODQzMCwiZXhwIjoxNjg1MDk0ODMwfQ.9qgoZSd5Tlb8HDmjp4uYn5qjQNq97eRL0j5Do-PTYC4
