GET localhost:7777/api/photos
Accept: application/json

> ./isSuccess.js

###

GET localhost:7777/api/photos/id/0
Accept: application/json

> ./isSuccess.js

###

GET localhost:7777/api/photos/name/car1.jpg
Accept: application/json

> ./isSuccess.js

###

DELETE localhost:7777/api/photos/2

> ./isNoContent.js

###

GET localhost:7777/api/photos/data/0
Accept: image/jpeg

> ./isSuccess.js

###

PUT localhost:7777/api/photos/0
Content-Type: application/json

{
  "newName": "newName.jpg"
}

> ./isNoContent.js
